# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: myf5-mysql
    ports:
      - "4306:3306"
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: myf5
