// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"goal", "assist", "save", "card"}},
		{Name: "match_events", Type: field.TypeInt},
		{Name: "player_events", Type: field.TypeInt},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "events_matches_events",
				Columns:    []*schema.Column{EventsColumns[2]},
				RefColumns: []*schema.Column{MatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "events_players_events",
				Columns:    []*schema.Column{EventsColumns[3]},
				RefColumns: []*schema.Column{PlayersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// MatchesColumns holds the columns for the "matches" table.
	MatchesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "date", Type: field.TypeTime},
		{Name: "goals_team1", Type: field.TypeInt},
		{Name: "goals_team2", Type: field.TypeInt},
	}
	// MatchesTable holds the schema information for the "matches" table.
	MatchesTable = &schema.Table{
		Name:       "matches",
		Columns:    MatchesColumns,
		PrimaryKey: []*schema.Column{MatchesColumns[0]},
	}
	// PlayersColumns holds the columns for the "players" table.
	PlayersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "global", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// PlayersTable holds the schema information for the "players" table.
	PlayersTable = &schema.Table{
		Name:       "players",
		Columns:    PlayersColumns,
		PrimaryKey: []*schema.Column{PlayersColumns[0]},
	}
	// TeamsColumns holds the columns for the "teams" table.
	TeamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "team", Type: field.TypeEnum, Enums: []string{"1", "2"}},
		{Name: "match_id", Type: field.TypeInt},
	}
	// TeamsTable holds the schema information for the "teams" table.
	TeamsTable = &schema.Table{
		Name:       "teams",
		Columns:    TeamsColumns,
		PrimaryKey: []*schema.Column{TeamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "teams_matches_teams",
				Columns:    []*schema.Column{TeamsColumns[2]},
				RefColumns: []*schema.Column{MatchesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TeamPlayersColumns holds the columns for the "team_players" table.
	TeamPlayersColumns = []*schema.Column{
		{Name: "team_id", Type: field.TypeInt},
		{Name: "player_id", Type: field.TypeInt},
	}
	// TeamPlayersTable holds the schema information for the "team_players" table.
	TeamPlayersTable = &schema.Table{
		Name:       "team_players",
		Columns:    TeamPlayersColumns,
		PrimaryKey: []*schema.Column{TeamPlayersColumns[0], TeamPlayersColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "team_players_team_id",
				Columns:    []*schema.Column{TeamPlayersColumns[0]},
				RefColumns: []*schema.Column{TeamsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "team_players_player_id",
				Columns:    []*schema.Column{TeamPlayersColumns[1]},
				RefColumns: []*schema.Column{PlayersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
		MatchesTable,
		PlayersTable,
		TeamsTable,
		TeamPlayersTable,
	}
)

func init() {
	EventsTable.ForeignKeys[0].RefTable = MatchesTable
	EventsTable.ForeignKeys[1].RefTable = PlayersTable
	TeamsTable.ForeignKeys[0].RefTable = MatchesTable
	TeamPlayersTable.ForeignKeys[0].RefTable = TeamsTable
	TeamPlayersTable.ForeignKeys[1].RefTable = PlayersTable
}
