// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Match is the predicate function for match builders.
type Match func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)
